version: '3'
services:
    webserver:
        image: puckel/docker-airflow
        restart: always
        environment:
            - FERNET_KEY=ydKflPZ2P2dq03Tziz7bMjMyoI4fKTlaFw8QmpqbP7E=
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs:/usr/local/airflow/logs
        ports:
            - "8080:8080"
